
<table width="100%" style="text-align:center;"  border="0" cellpadding="0" cellspacing="0" class="user-table_t">

  <tr class="tr2">
    <td>&nbsp;</td>
    <td colspan="6" align="center"><div class="tr3">Process List</div></td>
    <td align="center"><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesae')); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\add-button.png'); ?>" /></a></td>
  </tr>
  
<tr style="background:#cccccc;">
 <th>#</th>
 <th>Name</th>
 <th>Description</th>
 <th>Process<br />Date</th>
 <th>Process Plan</th>
 <th>Active</th>
 <th>Modify</th>
 <th>Delete</th>
</tr>
<?php
$sn=1;
foreach($this->processeslist as $vals)
 {
?>
<tr>
	<td><?php echo $sn; ?></td>
	<td><?php echo $vals->getName(); ?></td>
	<td><?php echo $vals->getDescription(); ?></td>
	<td><?php echo $vals->getProcessDate(); ?></td>
	<td><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesplanlist','processid'=>$vals->getId())); ?>" style="color:#666666;">Plans</a></td>
	<td><?php if($vals->getIsActive()==1) { echo 'Yes'; } else { echo 'No'; } ?></td>
	<td><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesae','EditId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\edit.png'); ?>" height="20" width="20" /></a></td>
	<td><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processeslist','DeleteId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\delete.png'); ?>" height="20" width="20" /></a></td>
</tr>
<?php $sn++; } ?>
</table>