

<table width="100%" style="text-align:center;" border="0" cellpadding="0" cellspacing="0" class="user-table_t">

  <tr class="tr2">
    <td>&nbsp;</td>
    <td colspan="5" align="center"><div class="tr3">Plan List</div></td>
    <td align="center"><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesplanae','processid'=>$this->processid)); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\add-button.png'); ?>" height="20" width="20" /></a></td>
  </tr>
  
  
<tr style="background-color:#CCCCCC;">
  <th>#</th>
  <th>Title</th>
  <th>Price</th>
  <th>Currency</th>
  <th>Active</th>
  <th>Edit</th>
  <th><!--Delete--></th>
</tr>
<?php
$sn=1;
foreach($this->processplanlist as $processplanlist)
 {
?>
<tr>
  <td><?php echo $sn; ?></td>
  <td><?php echo $processplanlist->Title; ?></td>
  <td><?php echo $processplanlist->Price; ?></td>
  <td><?php echo $processplanlist->Currency; ?></td>
  <td><?php  if($processplanlist->IsActive==1) { echo 'Yes'; } else {  echo 'No'; } ?></td>
  <td><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesplanae','processid'=>$this->processid,'EditID'=>$processplanlist->Id)); ?>" style="color:#666666;"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\edit.png'); ?>" height="20" width="20" /></a></td>
  <td><!--<a href="<?php // echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesplanlist','DeleteID'=>$processplanlist->Id)); ?>" style="color:#666666;"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\delete.png'); ?>" height="20" width="20" /></a>--></td>
</tr>
<?php $sn++; } ?>
</table>