<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Process Tracking System </title>

<link rel="stylesheet" type="text/css" media="all" href="<?php echo SITE_URL_ALLFILES;?>calendarfiles/jsDatePick_ltr.min.css" />
<script type="text/javascript" src="<?php echo SITE_URL_ALLFILES;?>calendarfiles/jsDatePick.min.1.3.js"></script>

<style type="text/css">
body{margin:0px; padding:0px;}
.process-header{width:100%; margin:auto; height:114px; background:#EFEFEF;}
.process-header-insi{width:860px; margin:auto; height:90px;}
.process-header-logo{ width:200px; height:80px; padding-top:10px; padding-left:10px; float:left;}
.process-header-right{width:640px; font-family:Tahoma, Geneva, sans-serif; height:60px; float:left; margin-top:25px; text-align:center;}
.process-header-right h2{font-size:20px; color:#2e3192;}

.process-header-contnt{width:860px; margin:auto;}
.frmde{width:300px; margin:auto; margin-top:30px;}




/*horizotally menu*/

.t_menu{width:100%; margin:auto; height:30px; border-bottom: 1px solid #BBB; border-top: 1px solid #BBB;}

.wireframeauramenu{

width: 600px;
margin:auto;
margin-top:5px;

}

.wireframeauramenu ul{

padding:0;
margin: 0;
text-align: left; 
overflow: hidden;
}

.wireframeauramenu ul li{
display: inline;
}

.wireframeauramenu ul li a{
color:#666;

padding: 0px 12px 12px 6px;
margin: 0px 40px 6px 0px;
text-decoration: none;
font-family:Arial, Helvetica, sans-serif;
font-size:14px;


}

.wireframeauramenu ul li a:hover{
color: black;
background: transparent url(<?php echo imagepathrestriction(SITE_PATH_All_Files.'\media\lightyellow.gif'); ?>) center center no-repeat; /*background of menu item onMouseover*/
}

/* horizotally menu closed */

.fst_box{border:1px solid #999; color:#666;}
.user-table{width:100%; font-family:Arial, Helvetica, sans-serif; color:#666; font-size:14px;}
.user-table_t{width:860px; margin-top:30px; border:1px solid #15163d;}
.user-table_t th{ background: url(<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\thbg.jpg'); ?>); background-repeat:repeat-x; font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:12px; height:30px;}
.tr4{ background:#e4e4e4; font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:12px; height:30px;}


.tr3{font-family:Arial, Helvetica, sans-serif; color:#2e3192; 
font-size:18px; font-weight:bold;}
.tr2{ background:url(<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\tr1.jpg'); ?>); background-repeat:repeat-x; font-family:Arial, Helvetica, sans-serif; color:#2e3192; 
font-size:18px; height:30px;}

.user-table_t td{font-family:Arial, Helvetica, sans-serif; color:#666; font-size:12px; text-align:center; height:24px;}
.buttn{width:70px; height:24px; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#fff; background:url(<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\button.png'); ?>); border:0px; }

.user-f{width:300px; margin:auto; text-align:center;}
.user-f h2{color:#2e3192; font-size:18px; font-family:Arial, Helvetica, sans-serif; margin-top:80px;}
.footer{width:100%; text-align:center; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#000; background:url(<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\bg-header.jpg'); ?>); background-repeat:repeat-x; height:100px; padding-top:10px; margin-top:70px; border-top: 1px solid #BBB;}
.footer a{color:#000; text-decoration:none; line-height:140%;}

.procss_frm{width:770px; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#666; margin:auto; }
.procss_frm_processform{width:470px; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#666;  }
.procss_frm_processform input{border:1px solid #999; color:#666; font-family:Arial, Helvetica, sans-serif; font-size:12px; }
.procss_frm_processform select{border:1px solid #999; color:#666; font-family:Arial, Helvetica, sans-serif; font-size:12px; }
.procss_frm_processform textarea{border:1px solid #999; color:#666; font-family:Arial, Helvetica, sans-serif; font-size:12px;}
.procss_frm_processform input[type="submit"]{width:70px; height:24px; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#fff; background:url(<?php echo SITE_URL_ALLFILES.'images/button.png'; ?>); border:0px; }

.p_input{border:1px solid #999; color:#666; width:150px;}
.p_input_s{border:1px solid #999; color:#666; width:155px;}


.dataTables_length { height:30px; }
.dataTables_length select{ border:1px solid #999; color:#666; }
.dataTables_filter { height:30px; }
.dataTables_filter input{ border:1px solid #999; color:#666; }

.button{width:70px; height:24px; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#fff; background:url(<?php echo SITE_URL_ALLFILES.'images/button.png'; ?>); border:0px; }
</style>


<script type="text/javascript" language="javascript">
function checksession()
{
var sessvar = '<?php echo $_SESSION['userid']; ?>';
if(sessvar==null || sessvar=="")
  {
   alert('Session expired');
   window.location.href = '/index/index/index';   
  }
  
}

setInterval('checksession()',5000);
</script>
</head>

<body>

<div class="process-header">
	<div class="process-header-insi">
		<div class="process-header-logo"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\logo-1.png'); ?>" alt="" /></div>
			<div class="process-header-right"><h2>PROCESS TRACKING SYSTEM</h2></div>

<div style="text-align:right;padding:15px;">
<font face="Comic sans MS" size="2">Welcome &nbsp;&nbsp;<?php echo ucfirst($_SESSION['userName']); ?> &nbsp;&nbsp;
&nbsp;&nbsp;|&nbsp;&nbsp;
<a style="color:#000000;text-decoration:none;" href="<?php echo SITE_URL_PUBLIC_P; ?>index/index/logout" style="text-decoration:none;">Logout</a> </font><br /></div>

<div style="height:12px;"></div>

	</div>
    </div>
    
    
    
<div class="t_menu">
    
    <div class="wireframeauramenu">
<ul>

<?php

 if($_SESSION['userttypeid']==0 or $_SESSION['userttypeid']==1) { ?>
<li><a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userlist')); ?>">Users</a></li>

<?php if($_SESSION['userttypeid']==0) { ?>
<li><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processeslist')); ?>">Process</a></li>
<?php } ?>
<li><a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userreport')); ?>">User Report</a></li>
<?php } ?>

<li><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processforms')); ?>">Process Forms</a></li>
<li><a href="http://121.242.207.115/iolo" target="_blank">IOLO</a></li>


</ul>
</div>

    </div>
    
 
    
<div class="process-header-contnt">
 <?php echo $this->layout()->content ?>
<div style="clear:both;"></div>
</div>


    <div class="footer">
<a href="/privacy.html">Privacy Policy</a> | <a href="/legal.html">Legal   Statements</a> | <a href="/resources.html">Resources</a> | <a href="http://blogs.cyfuture.com/">Blogs</a> <br />
Copyright© 2012 All rights   Reserved at Cyber Futuristics (India) Pvt. Ltd. <br />
Website Design and Developed   by <a href="/">Cyber Futuristics</a></></div>
</body>
</html>
