<style>
.conatiner_body {
    width: 888px;
}
.conatiner_body_right {
    width: 642px;
}
</style>

<table width="100%" style="text-align:center;" border="0" cellpadding="0" cellspacing="0" class="user-table_t">

  <tr class="tr2">
    <td>&nbsp;</td>
    <td colspan="6" align="center"><div class="tr3">User List</div></td>
    <td align="center"><a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userae')); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\add-button.png'); ?>" height="20" width="20" /></a></td>
  </tr>
  
  
<tr>
 <th>#</th>
 <th>Name</th>
 <th>Username</th>
<!-- <th>Password</th>-->
 <th>Role<br/>Type</th>
 <th>Active</th>
 <th>Processes</th>
 <th>Modify</th>
 <th>
 <?php if($_SESSION['userttypeid']=="0") { ?>
 Delete
 <?php } ?>
 </th>
</tr>
<?php
$sn=1;
foreach($this->userlist as $vals)
 {
?>
<tr>
	<td><?php echo $sn; ?></td>
	<td><?php echo $vals->getName(); ?></td>
	<td><?php echo $vals->getUsername(); ?></td>
	<!--<td><?php //echo $vals->getPassword(); ?></td>-->
	<td><?php if($vals->getUserType()==0) { echo 'Super Admin'; } elseif($vals->getUserType()==1) { echo 'Admin'; } elseif($vals->getUserType()==2) { echo 'User'; } elseif($vals->getUserType()==3) { echo 'Supervisor'; } ?></td>
	<td><?php if($vals->getIsActive()==1) { echo 'Yes'; } else { echo 'No'; } ?></td>
	<td><a href="<?php echo $this->url(array('module'=>'main','controller'=>'processes','action'=>'processesassign','PUId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\process.png'); ?>" height="20" width="20" /></a></td>
	<td>
	
	<?php if($vals->getUserType()=="0") { 
	if($_SESSION['userttypeid']==0)
	{
	?>
	<a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userae','EditId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\edit.png'); ?>" height="20" width="20" /></a>
	<?php } } else { ?>
		<a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userae','EditId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\edit.png'); ?>" height="20" width="20" /></a>
	<?php } ?>
	
	</td>
	<td>
	<?php if($vals->getId()!="0") { ?>
	 <?php if($_SESSION['userttypeid']=="0") { ?>
	<a href="<?php echo $this->url(array('module'=>'main','controller'=>'users','action'=>'userlist','DeleteId'=>$vals->getId())); ?>"><img src="<?php echo imagepathrestriction(SITE_PATH_All_Files.'\images\delete.png'); ?>" height="20" width="20" /></a>
	<?php } } ?>
	</td>
</tr>
<?php $sn++; } ?>
</table>